name: Check for Deprecated Packages and Auto-upgrade Packages

on:
  push:
    branches:
      - develop
  schedule:
    - cron: '0 */6 * * *'

permissions:
  actions: write
  checks: write
  contents: write

env:
  slack_channel: '#alert'
  slack_username: 'Github Actions'
  node_version: '18.x'

jobs:
  upgrade-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: "yarn"
      - name: Install packages
        run: yarn install
      - name: Upgrade packages
        run: yarn upgrade
      - name: Test
        run: yarn test
      - name: Test build
        run: yarn build && touch ./dist/.gitkeep
      - name: Commit changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.email ${{ github.actor }}@users.noreply.github.com
            git config user.name "BOT.${{ github.actor }}"
            git add .
            git commit -m "Auto-upgraded packages $(date +'%Y-%m-%d %H:%M:%S')" --allow-empty
            git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
          else
            echo "No changes to commit"
          fi
  check-deprecated:
    needs: upgrade-packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: develop
      - name: Install Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          cache: "yarn"
      - name: Install packages
        run: yarn install
      - name: Check for deprecated packages
        id: check
        run: yarn outdated
        continue-on-error: true
      - name: Post to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: 'failure'
          text: |
            Deprecated package(s) found!
            -> ${{ github.repository }}
            -> run `yarn outdated` and `yarn upgrade [--latest]` to fix it.
          channel: ${{ env.slack_channel }}
          username: ${{ env.slack_username }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ always() && steps.check.outcome != 'success' }}
